version: "3.8"
services:
    app:
        build: .
        environment:
            ENABLE_CORS: 1
            REDIS_HOST: "redis"
            ROOT_URL: "http://localhost:8000"
            SESSION_SECRET_KEY: 'N1BKhJLnBqLpexOZdklsfDKFJDKFadsfs9a3r324YB7B73AglRmrHMDQ9RhXz35' # create a new one
        links:
            - redis
        ports:
            - "8000:8000"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
            interval: 1s
            timeout: 3s
            retries: 60

    redis:
        image: redis:latest
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 1s
            timeout: 3s
            retries: 30
