version: "3.8"
services:
    app:
        image: siteworxpro/requestbin:latest
        environment:
            ENABLE_CORS: 1
            REDIS_HOST: "redis"
            ROOT_URL: "http://localhost:8000"
            SESSION_SECRET_KEY: '33W7JxP8h0qp12imYkn153pzuniAJOyfylzNxkRHP0xENafLOvuE9Bbakwc9n0pe' # change me
        links:
            - redis
        ports:
            - "8000:8000"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
            interval: 1s
            timeout: 3s
            retries: 60

    redis:
        image: redis:latest
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 1s
            timeout: 3s
            retries: 30
